version: '3.7'

services:
  chatee-db:
    container_name: chatee_mongo
    image: mongo
    restart: always
    command: [ '--replSet', 'rs0', '--bind_ip_all', '--port', '27017' ]
    ports:
      - '27017:27017'
    volumes:
      - chatee-data:/chatee/data/db

  db-init:
    image: mongo
    depends_on:
      - chatee-db
    command: >
      /bin/bash -c "
      while ! echo 'try { rs.status() } catch (err) { rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"127.0.0.1:27017\"}]}); }' | mongosh --host chatee-db --port 27017 --quiet; do
      sleep 5;
      done;"
    restart: on-failure

volumes:
  chatee-data:
